/*
创建人：神数不神
创建日期：2024-6-9
无修正
*/
#include "qutil.h"
namespace GameClient::Tool { 
	QMap<quint64,QString> QUtil::attributeMap = {
		{ATTRIBUTE_EARTH, TEXT_ATTRIBUTE_EARTH},
		{ATTRIBUTE_WATER, TEXT_ATTRIBUTE_WATER},
		{ATTRIBUTE_FIRE, TEXT_ATTRIBUTE_FIRE},
		{ATTRIBUTE_WIND, TEXT_ATTRIBUTE_WIND},
		{ATTRIBUTE_LIGHT, TEXT_ATTRIBUTE_LIGHT},
		{ATTRIBUTE_DARK, TEXT_ATTRIBUTE_DARK},
		{ATTRIBUTE_DEVINE, TEXT_ATTRIBUTE_DEVINE}
	};
	QMap<quint64,QString> QUtil::raceMap = { 
		{RACE_WARRIOR, TEXT_RACE_WARRIOR},
		{RACE_SPELLCASTER, TEXT_RACE_SPELLCASTER},
		{RACE_FAIRY, TEXT_RACE_FAIRY},
		{RACE_FIEND, TEXT_RACE_FIEND},
		{RACE_ZOMBIE, TEXT_RACE_ZOMBIE},
		{RACE_MACHINE, TEXT_RACE_MACHINE},
		{RACE_AQUA, TEXT_RACE_AQUA},
		{RACE_PYRO, TEXT_RACE_PYRO},
		{RACE_ROCK, TEXT_RACE_ROCK},
		{RACE_WINDBEAST, TEXT_RACE_WINDBEAST},
		{RACE_PLANT, TEXT_RACE_PLANT},
		{RACE_INSECT, TEXT_RACE_INSECT},
		{RACE_THUNDER, TEXT_RACE_THUNDER},
		{RACE_DRAGON, TEXT_RACE_DRAGON},
		{RACE_BEAST, TEXT_RACE_BEAST},
		{RACE_BEASTWARRIOR, TEXT_RACE_BEASTWARRIOR},
		{RACE_DINOSAUR, TEXT_RACE_DINOSAUR},
		{RACE_FISH, TEXT_RACE_FISH},
		{RACE_SEASERPENT, TEXT_RACE_SEASERPENT},
		{RACE_REPTILE, TEXT_RACE_REPTILE},
		{RACE_PSYCHO, TEXT_RACE_PSYCHO},
		{RACE_DEVINE, TEXT_RACE_DEVINE},
		{RACE_CREATORGOD, TEXT_RACE_CREATORGOD},
		{RACE_WYRM, TEXT_RACE_WYRM},
		{RACE_CYBERSE, TEXT_RACE_CYBERSE}
	};
	QMap<quint64,QString> QUtil::typeMap = { 
		{TYPE_MONSTER, TEXT_TYPE_MONSTER},
		{TYPE_SPELL, TEXT_TYPE_SPELL},
		{TYPE_TRAP, TEXT_TYPE_TRAP},
		{TYPE_NORMAL, TEXT_TYPE_NORMAL},
		{TYPE_EFFECT, TEXT_TYPE_EFFECT},
		{TYPE_FUSION, TEXT_TYPE_FUSION},
		{TYPE_RITUAL, TEXT_TYPE_RITUAL},
		{TYPE_TRAPMONSTER, TEXT_TYPE_TRAPMONSTER},
		{TYPE_SPIRIT, TEXT_TYPE_SPIRIT},
		{TYPE_UNION, TEXT_TYPE_UNION},
		{TYPE_DUAL, TEXT_TYPE_DUAL},
		{TYPE_TUNER, TEXT_TYPE_TUNER},
		{TYPE_SYNCHRO, TEXT_TYPE_SYNCHRO},
		{TYPE_TOKEN, TEXT_TYPE_TOKEN},
		{TYPE_QUICKPLAY, TEXT_TYPE_QUICKPLAY},
		{TYPE_CONTINUOUS, TEXT_TYPE_CONTINUOUS},
		{TYPE_EQUIP, TEXT_TYPE_EQUIP},
		{TYPE_FIELD, TEXT_TYPE_FIELD},
		{TYPE_COUNTER, TEXT_TYPE_COUNTER},
		{TYPE_FLIP, TEXT_TYPE_FLIP},
		{TYPE_TOON, TEXT_TYPE_TOON},
		{TYPE_XYZ, TEXT_TYPE_XYZ},
		{TYPE_PENDULUM, TEXT_TYPE_PENDULUM},
		{TYPE_SPSUMMON, TEXT_TYPE_SPSUMMON},
		{TYPE_LINK, TEXT_TYPE_LINK}
	};
}