/*
创建人：神数不神
创建日期：2024-6-9
无修正
*/
#include "qutil.h"
namespace GameClient::Tool { 
	QMap<quint64,QString> QUtil::attributeMap = {
		{ATTRIBUTE_EARTH, TEXT_ATTRIBUTE_EARTH},
		{ATTRIBUTE_WATER, TEXT_ATTRIBUTE_WATER},
		{ATTRIBUTE_FIRE, TEXT_ATTRIBUTE_FIRE},
		{ATTRIBUTE_WIND, TEXT_ATTRIBUTE_WIND},
		{ATTRIBUTE_LIGHT, TEXT_ATTRIBUTE_LIGHT},
		{ATTRIBUTE_DARK, TEXT_ATTRIBUTE_DARK},
		{ATTRIBUTE_DEVINE, TEXT_ATTRIBUTE_DEVINE}
	};
	QMap<quint64,QString> QUtil::raceMap = { 
		{RACE_WARRIOR, TEXT_RACE_WARRIOR},
		{RACE_SPELLCASTER, TEXT_RACE_SPELLCASTER},
		{RACE_FAIRY, TEXT_RACE_FAIRY},
		{RACE_FIEND, TEXT_RACE_FIEND},
		{RACE_ZOMBIE, TEXT_RACE_ZOMBIE},
		{RACE_MACHINE, TEXT_RACE_MACHINE},
		{RACE_AQUA, TEXT_RACE_AQUA},
		{RACE_PYRO, TEXT_RACE_PYRO},
		{RACE_ROCK, TEXT_RACE_ROCK},
		{RACE_WINDBEAST, TEXT_RACE_WINDBEAST},
		{RACE_PLANT, TEXT_RACE_PLANT},
		{RACE_INSECT, TEXT_RACE_INSECT},
		{RACE_THUNDER, TEXT_RACE_THUNDER},
		{RACE_DRAGON, TEXT_RACE_DRAGON},
		{RACE_BEAST, TEXT_RACE_BEAST},
		{RACE_BEASTWARRIOR, TEXT_RACE_BEASTWARRIOR},
		{RACE_DINOSAUR, TEXT_RACE_DINOSAUR},
		{RACE_FISH, TEXT_RACE_FISH},
		{RACE_SEASERPENT, TEXT_RACE_SEASERPENT},
		{RACE_REPTILE, TEXT_RACE_REPTILE},
		{RACE_PSYCHO, TEXT_RACE_PSYCHO},
		{RACE_DEVINE, TEXT_RACE_DEVINE},
		{RACE_CREATORGOD, TEXT_RACE_CREATORGOD},
		{RACE_WYRM, TEXT_RACE_WYRM},
		{RACE_CYBERSE, TEXT_RACE_CYBERSE}
	};
}